### ISSUE TITLE
Feature request: Connect to own uci chess engine

### ISSUE THREAD

**Issue by francogrex** [Hakorr/A.C.A.S#10]
It would be good if we can use own chess engine (for example, not the default one, but an executable uci chess engine of choice running on the users's own computer - it could be a Stockfish, Berserk etc..)

**Comment by Hakorr** [comment]
> an executable uci chess engine of choice running on the users's own computer

I don't think it's possible to establish connection to localhost from the website.

I will add more JS/WASM based engines in the future.
