### ISSUE TITLE
Add "termometer" with evaluation

### ISSUE THREAD

**Issue by sdavidg** [Hakorr/A.C.A.S#2]
Add "termometer" with evaluation
![imagen](https://github.com/Hakorr/A.C.A.S/assets/4955944/a9a6e3ba-c2cc-4116-a9e5-7ac9451ac2af)

**Comment by Hakorr** [comment]
Do you mean that you want to see the exact number of the eval?

I think it's good to note that the eval is not completely accurate, as A.C.A.S doesn't run any separate eval calculations, rather just takes eval from the move suggestion. This might be completely different from a regular eval you'd see on other GUIs. Therefore, knowing the exact number of the eval might not be of any benefit.

I'm very new to chess programming and chess in general, so I understand this method might be a bit strange.
