### ISSUE TITLE
FATAL ERROR: COI failed to enable SharedArrayBuffer, report issue to GitHub!

### ISSUE THREAD

**Issue by Yibbibi** [Hakorr/A.C.A.S#3]
Error message popped up in the A.C.A.S. tab, told me to report so here I am.

On Firefox117 (OS: Windows10 desktop)

Tried with Greasemonkey and Violentmonkey, got the same result.

Seems that none of the feature shown on the A.C.A.S. page screenshots/description appear to work - visiting chess.com/lichess and playing a game appears completely ordinary.

Here's a screenshot of the error:
![Untitled](https://github.com/Hakorr/A.C.A.S/assets/143988708/652b16e9-6176-47d0-a2bc-f17e0c5931b3)

**Comment by Hakorr** [comment]
A.C.A.S seems to work for me on Windows 10, the latest version of Firefox & Violentmonkey. By the way, that error isn't related to the userscript, so it shouldn't matter which userscript manager you're using.

Did this happen just once, or is happening constantly? Have you tried using a Chromium based browser (e.g. Chrome)? Try playing against the same engine [here](https://fairyground.vercel.app/), if it doesn't work, your device might be the issue.
